### ISSUE TITLE
Sprout email interferes with standard P&T contactform

### ISSUE THREAD

**Issue by noregt** [barrelstrength/craft-sprout-email#107]
### Description
When both the sprout email and the P&T contact form are installed on a basic Craft install, on submitting the P&T form, the system throws the following error:

"Creating default object from empty value"
in /vendor/barrelstrength/sprout-email/src/services/SentEmails.php at line 75
$infoTable->senderName = $fromName;

public_html/vendor/barrelstrength/sprout-email/src/SproutEmail.php barrelstrength\sproutemail\services\SentEmails::logSentEmail()
 at line 124 – 
SproutEmail::$app->sentEmails->logSentEmail($event);

### Additional info

- Craft version: 3.1.19
- PHP version: 7.1.20
- Database driver & version: mysql
- Plugins & versions: 4.0.0-beta.13

**Comment by BenParizek** [comment]
Thanks for reporting @noregt.

We're looking into it.

**Comment by pdaleramirez** [comment]
This is a bug and i fixed this on this commit https://github.com/barrelstrength/craft-sprout-email/commit/7a4cd060bb141b8e2847827018df9d1b83cfd22f this will also fixed other modules or plugin that use the send email method.

**Comment by noregt** [comment]
Thank you! When will this be an update in craft?

**Comment by BenParizek** [comment]
@noregt The latest release of Sprout Email (released yesterday) includes a fix for this.
