### ISSUE TITLE
When a User is Created Event should be able to send when no User Groups exist

### ISSUE THREAD

**Issue by noregt** [barrelstrength/craft-sprout-email#108]
Original Title:
**Sprout email not sending notification when user is saved or created**

### Description
On a standard Craft install, sprout email will not send a notification when a user is created.
A notification for a deleted user does work.

Both have the same settings, except for the event of course. It doesn't matter if "Send to admins?" is checked or not.

The user created notification is also not listed in the Sent emails list, whereas the deleted user notification is.

Oddly enough, in the sent emails list you will see the system notification e-mails like 'Activate your account' when this is set in the user settings (I've tested the notification with 'Verify email addresses?' on and off). The password reset mail will also be listed there.

I've noticed one occasion where the system was able to catch the user creation event and send a notification, so it does not fail 100%.

### Steps to reproduce

1. On a clean craft install, setup a basic notification 'When a user is saved' 
2. Create a new user.

### Additional info

- Craft version: 3.1.19
- PHP version: 7.1.20
- Database driver & version: mysql
- Plugins & versions: Sprout email 4.0.0-beta.13

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ip0z)

**Comment by BenParizek** [comment]
Hi @noregt 

We just released a handful of updates to Sprout Email yesterday. We didn't address this issue specifically but did address several issues that could be related. Can you confirm if this is still happing for you? If so, I may need to ask you to send over your database to sprout@barrelstrengthdesign.com so we can take a closer look as we try to recreate the issue.

**Comment by noregt** [comment]
I'm afraid this doesn't make a difference. Just tested on two installs. Will send you the details.

**Comment by noregt** [comment]
I did notice a consistency: the notification will be sent if the new user is an admin. Also the first time when the user is upgraded to admin (with the checkbox 'When user is updated?' checked of course). But not the downgrade back or the second upgrade to admin.
Also, test emails from Craft are still saved as well.

**Comment by BenParizek** [comment]
Thanks @noregt. We'll dig in more.

Note to self:
[Ticket with database](https://app.frontapp.com/open/cnv_1bocfez)

**Comment by BenParizek** [comment]
@noregt The issue here seems to be that this Event currently requires one User Group to exist and to have that group or the "All" option selected. I'm going to consider this a bug and we'll revisit those settings so you don't have to create an unnecessary group if you don't need it. 

Right now, you should be able to work around this issue by creating a temporary user group and selecting the "All" groups option on the event.

**Comment by noregt** [comment]
I do have user groups in the live site, where the same problem persists. Just tested this again.

**Comment by noregt** [comment]
Sorry now it did work... I'll keep on testing to see what really happens.

**Comment by BenParizek** [comment]
I'm closing this ticket out for now as it sounds like things are working again for you. If something else pops up, feel free to open a new ticket.
