### ISSUE TITLE
Using twig include and extends in email templates under Craft 3

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-email#111]
### Description

In an original Craft 2 project, I used Sprout Emails with custom emails templates. Each template was set to a path within the folder `_sproutemails` e.g. `_sproutemails/notification-template.html`,  `_sproutemails/another-template.html` and so on, along with it's accompanying txt variant. The folder was present within the root Craft templates directory. To save duplication in the HTML templates, I created some extendable layouts with Twig that created the base HTML boilerplate and blocks for the main sections like header, main content, footer etc. This worked fine under Craft 2. You could specify an extends to a template path from the root Craft templates folder e.g. `craft/templates/_sproutemails/layouts/boilerplate.twig` with no problems, and was called as `{% extends '_sproutemails/layouts/boilerplate' %}`

Migrating to Craft 3, the first change appears to be that all custom templates must point to a location that loads an `email.twig` file, it seems it can be in any directory, but it must be named email.html or email.twig. Given the Sprout Email migration updated the template paths for each of the Craft 2 notifications to `_sproutemails/previous-template-name` (without the .html extension), I figured if I create that name as a directory and put an email.twig file in there it would load, it does. However, the setup of calling an extends to a template (now sitting in a folder one above this new structure) now cannot be loaded due to not being found. This suggests, that the template path is locked down to the directory the email.twig/html file is present in. Under Craft 2 I could call `_sproutemails/layouts/boilerplate` regardless of what directory level and it would be found, under Craft 3, the template search path appears to be different.

Would it possible to clarify if using Twig includes/extends is possible in this way under Craft 3 ? Or do I need to re-think the approach? I'm happy to change the approach, but I'm just wanting to understand the Craft 3 setup a bit better before proceeding!

Many thanks!

### Additional info

- Craft version: 3.1.23
- PHP version: 7.1
- Plugins & versions: v4.0.0-beta.15

**Comment by BenParizek** [comment]
Related: https://github.com/barrelstrength/craft-sprout-forms/issues/164

**Comment by BenParizek** [comment]
Hey @jamesmacwhite 

I just noticed that you opened a similar request for this regarding Sprout Forms Email Notifications (https://github.com/barrelstrength/craft-sprout-forms/issues/164). Both Sprout Email and Forms are using the same code under the hood for Notifications so if we can address this in one place we'll be addressing it in both. 

I'll let you know what we determine once we have a chance to look into this.

**Comment by jamesmacwhite** [comment]
@BenParizek Hey Ben. Thanks for chiming in. That's correct, a similar behaviour occurs with sprout form/field templates as well. However, in the case of Sprout Email on Craft 2, the template path didn't seem to have the same restrictions as it does in Craft 3, so I was flagging that mainly as a behaviour change while looking at migrating an existing project that has email templates originally designed around the Craft 2 version.

Thanks!

**Comment by BenParizek** [comment]
@jamesmacwhite The latest release of Sprout Forms v3.9.0 and Sprout Email v4.2.0 addresses the Email Template rendering folder issue. You can now use `{% extends %}` or `{% include %}` and target any file in your `templates/` folder to support your `email.twig` file.

**Comment by jamesmacwhite** [comment]
@BenParizek Sorry for never acknowledging this! That's great news and most useful for our Craft 3 migration, thank you!
