### ISSUE TITLE
When a user is saved Event issue

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#113]
<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_iwhn)

**Comment by medoingthings** [comment]
Not sure what the details are on this. But in my Craft installation (Latest Craft 3, upgraded from latest Craft 2) the "User saved" event in combination with "User created" doesn't seem to trigger an E-Mail.

**Comment by BenParizek** [comment]
Thanks @medoingthings. We've been able to recreate this and will have a release out soon.

**Comment by BenParizek** [comment]
@medoingthings This issue has been resolved in the latest release, Sprout Email v4.0.0.
