### ISSUE TITLE
Changing event type makes notification uneditable

### ISSUE THREAD

**Issue by medoingthings** [barrelstrength/craft-sprout-email#117]
### Description
When changing the event type from "When a User is Saved" to "When a User is deleted" an error is thrown and the notification can’t be edited anymore. Error:

```
Setting unknown property: barrelstrength\sproutemail\events\notificationevents\UsersDelete::userGroupIds
```

### Steps to reproduce

1. Create a new notification with the event "When a User is Saved"
2. Set "User Groups" setting to "All" and save
3. Change the event to "When a User is deleted"
4. Try to edit the notification again – the above mentioned error should be thrown

### Additional info

- Craft version: Craft Pro 3.1.28
- PHP version: 7.1.2
- Database driver & version: MySQL
- Plugins & versions: Sprout Email 4.0.0-beta.18

**Comment by BenParizek** [comment]
@medoingthings This issue has been resolved in the latest release, Sprout Email v4.0.0.
