### ISSUE TITLE
For Loop in notification template wraps output in <pre> and <code> tags

### ISSUE THREAD

**Issue by GaryReckard** [barrelstrength/craft-sprout-email#123]
### Description (screenshots, logs, ...)
When using a for loop in email notification template, the resulting email has `<pre>` and `<code>` html tags wrapped around the output of the for loop.

So, given this code in my notification template:
```
<b>What ethnicities will you consider?:</b> 
	{% for option in object.adopt_child_match_ethnicity %}
		{{ option.label }}, 
		{% if loop.last %}
			{{ option.label }}
		{% endif %}			
	{% endfor %}	
``` 
The resulting email contains:
```
<p><br>
<b>What ethnicities will you consider?:</b> </p>
<pre><code>	African American/Black, 
				
	Asian, 
				
	Hispanic/Latino
	
</code></pre>
```

### Steps to reproduce

1. Have a section that contains a field that with multiple values, like checkboxes.
2. Create an entry that has multiple values for that field.  
3. Create an email notification template containing a for-loop that iterates over entry data
4. Fire off a 'test email' for that notification, and view the output.

### Additional info

- Craft version: 3.2.5
- PHP version: 7.2.19
- Database driver & version:  MySQL 5
- Plugins & versions: Sprout Email 4.0.4

**Comment by andrelopez** [comment]
Sorry, we're unable to recreate this issue. Are you still having this behavior?

**Comment by BenParizek** [comment]
@GaryReckard As we haven't heard back from you here and haven't been able to recreate this issue ourselves, I'm going to close this out.

Feel free to update this thread with more info if we can help troubleshoot further. Sprout Email is definitely not intentionally adding any HTML tags into the templates around for loops or anything like that. I'm not sure what would be but might test the email provider or client to see if the issue could be recreated from another email source.
