### ISSUE TITLE
Previewing Commerce emails show blank screen

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-email#126]
Trying to troubleshoot the Sent Emails for all Commerce emails being blank when you open the preview. Other system emails (forgot password, etc) work just fine.

We're using MJML to generate the HTML, but I don't believe that's anything to do with this, as its just a Twig filter - the emails are generating fine. Resending also doesn't work.

Diving into the specifics of the issue, it seems that the sent email's `htmlBody` and `body` are null (in `_special/preview.twig`).

Looking at how this is stored when logging the sent email (https://github.com/barrelstrength/craft-sprout-email/blob/1594a793ac463d8301da2941b9230d7e641c8830/src/services/SentEmails.php#L216-L226) its only checking for children in the SwiftMailer message. Which in this case, is an empty array.

The HTML content is actually available via `$message->getSwiftMessage()->getBody()`. As such, amending this code to:

```
$body = $message->getSwiftMessage()->getBody();

if ($body) {
    $sentEmail->htmlBody = $body;
    $sentEmail->body = $body;
}

if ($children) {
    foreach ($children as $child) {
        if ($child->getContentType() == 'text/html') {
            $sentEmail->htmlBody = $child->getBody();
        }

        if ($child->getContentType() == 'text/plain') {
            $sentEmail->body = $child->getBody();
        }
    }
}
```

Caters for both cases, and seems to work correctly for me. Can you reproduce this?

### Additional info

- Craft version: 3.3.9
- PHP version: 7.1
- Plugins & versions: Commerce 2.1.13, Sprout Email 4.0.5

**Comment by gojira32** [comment]
Any ETA on this guys. Pretty major issue with this plugin, can't really use it for it's intended purpose.

Also, we can't re-send emails which would be very helpful, say if a customer entered the incorrect email address during checkout...

**Comment by BenParizek** [comment]
Thanks for reporting. We'll address this as soon as we can and update this thread once we do.

**Comment by gojira32** [comment]
@BenParizek Any progress on this?

**Comment by BenParizek** [comment]
@gojira32 I'm back this week after a few weeks of travel. I'm turning my focus to all of our outstanding bugs and will update when I have more.

**Comment by gojira32** [comment]
@BenParizek Any update on this?

**Comment by BenParizek** [comment]
@engram-design @gojira32 

I've just released updates with support for Craft 3.4 and I'm not able to recreate this issue in my tests (testing on Craft 3.4, Commerce 3). When you have a chance, can you test on the latest and let me know if you still have the issue?

If so, I can implement something like Josh's proposed solution but I will need to dig in a bit more to understand the difference between the main and child email versions and which should take priority.

**Comment by engram-design** [comment]
@BenParizek We're not at the stage where we can upgrade to Craft 3.4/Commerce 3.x, but it looks like this is working, thanks to the commit https://github.com/barrelstrength/craft-sprout-email/commit/d6e8f77b62bffe749eba32f743034dd57342cf7a

Any chance this can be back-tracked to a Craft 3.3 compatible version?

**Comment by BenParizek** [comment]
I've created a branch for Craft v3.3 if you can't update to v3.4 yet:
https://github.com/barrelstrength/craft-sprout-email/releases/tag/v4.0.7

**Comment by engram-design** [comment]
Sorry to bring this up again, but its still an issue on 4.4.0. Now that its all been extracted to [craft-sprout-base-sent-email](https://github.com/barrelstrength/craft-sprout-base-sent-email/blob/v1/src/services/SentEmails.php) its a bit trickier to fix.

The below works:
```
$children = $message->getSwiftMessage()->getChildren();

$body = $message->getSwiftMessage()->getBody();

// Added
if ($body) {
    $sentEmail->htmlBody = $body;
    $sentEmail->body = $body;
}

if ($children) {
    foreach ($children as $child) {
        if ($child->getContentType() == 'text/html') {
            $sentEmail->htmlBody = $child->getBody();
        }

        if ($child->getContentType() == 'text/plain') {
            $sentEmail->body = $child->getBody();
        }
    }
} else {
    // Get body from message
    $body = $message->getSwiftMessage()->getBody();

    if ($body) {
        $sentEmail->htmlBody = $body;
        $sentEmail->body = $body;
    }
}
```

**Comment by BenParizek** [comment]
Thanks for the example @engram-design. I'll review and get this back in place, or updated. I'm not sure what might have changed during the migration as it was mostly just architectural.

**Comment by BenParizek** [comment]
@engram-design I've updated the logic in the latest release (v4.4.2) to default to using that body first and fallback to the children if nothing is found. In my tests, that seems to still be working with the most common types of emails sent. I'm still not clear on why Commerce is behaving differently than the other plugins here, but hopefully, this update can put this to rest.

**Comment by engram-design** [comment]
Thanks @BenParizek much appreciated
