### ISSUE TITLE
Change the default sorting on Sent Email list to Date Sent Descending

### ISSUE THREAD

**Issue by ldennison-bsd** [barrelstrength/craft-sprout-email#127]
Currently, it seems the default sorting on the Sent Emails list is on the Date Sent column, which is fine, but in Ascending order. This should be changed to Descending because people are most frequently going to want to see the most recent sent emails rather than their older history.

**Comment by BenParizek** [comment]
@ldennison-bsd This has been resolved in Sprout Email v4.1.4
