### ISSUE TITLE
Notifications list view broken in Craft 3.4.3

### ISSUE THREAD

**Issue by cdfwebsolutions** [barrelstrength/craft-sprout-email#135]
In Craft 3.4.3/Sprout Email 4.0.6, the main interface for listing existing notifications (admin/sprout-email/notifications) is empty, although notifications do exist and are working.

![image](https://user-images.githubusercontent.com/1706919/73806739-5121eb80-4798-11ea-9a27-bdfd70bf0388.png)

There is a js error on that page:
`Uncaught TypeError: Cannot read property 'find' of null  Craft.js:3056`
though that may just be because it is not getting any data.

We can manually access the edit interface for email notifications by going directly to the edit URL, e.g.: admin/sprout-email/notifications/edit/961

### Additional info

- Craft version: 3.4.3
- PHP version: 7.2.27
- Database driver & version:  MySQL 5.6.45
- Plugins & versions: Sprout Email 4.0.6

**Comment by BenParizek** [comment]
@cdfwebsolutions We'll have a release out soon with Craft 3.4 compatibility updates. I'll update this thread when we do.

**Comment by BenParizek** [comment]
@cdfwebsolutions We've just released Sprout Email v4.1.1 that adds Craft 3.4 support and resolves this issue.

**Comment by cdfwebsolutions** [comment]
Wow - that was fast. Thanks!

**Comment by cdfwebsolutions** [comment]
...and I can confirm that the issue is fixed. Thanks again :)

**Comment by BenParizek** [comment]
Onward!
