### ISSUE TITLE
Sprout Email stops Feed Me from processing

### ISSUE THREAD

**Issue by AndrewMac** [barrelstrength/craft-sprout-email#142]
### Description (screenshots, logs, ...)

Whenever I run Feed Me when Sprout Email is enabled, the feed does not work.
I get the following error message: 

session_set_cookie_params(): Cannot change session cookie parameters when headers already sent - Session.php: 399.

If I disable Sprout Email the feed works as expected.

I have disabled all plugins, one by one, in order to isolate the cause, and it really does appear to be Sprout Email that causes this issue. Any ideas why? And do you think there's any fix?

### Steps to reproduce

1. Enable Feed Me and Sprout Email
2. Run Feed; it doesn't work (see error message above)
3. Disable Sprout Email
4. Feed works

### Additional info

- Craft version: 3.4.5 Pro
- PHP version: 7.4.2 (but happens under 7.3 too)
- Database driver & version: SQL
- Plugins & versions: Sprout Email 4.1.2 (and the just-released 4.1.3), Feed Me 4.2.0.1

**Comment by BenParizek** [comment]
Thanks @AndrewMac. I can recreate this issue. It seems our check to avoid some code on console requests isn't being respected. I'll update this thread when we have a solution.

**Comment by AndrewMac** [comment]
Hi Ben, thanks for looking into things! :-)

**Comment by BenParizek** [comment]
@AndrewMac This has been resolved in Sprout Email v4.1.4

**Comment by AndrewMac** [comment]
Thank you! :-)
