### ISSUE TITLE
Mailing List as recipient

### ISSUE THREAD

**Issue by johnj24** [barrelstrength/craft-sprout-email#145]
I've learned through documentation that I can set up a report in Sprout Reports and use it as a mailing list in Sprout Email notifications. However, I'm not seeing any reference to how I actually do it? Can you offer an example of what to put in the recipients input?

Thanks!

**Comment by BenParizek** [comment]
@johnj24 I'll try to improve our docs on this.

To use a Report as a Mailing List you'll need to have Sprout Reports Pro installed. 

In Sprout Reports, when you create a Report you will see a setting for "Email Column"  in the right sidebar (https://share.barrelstrength.co/v1urPY1N). You will want to set that Email Column to match the heading of the column in your report results that you want to use as the email in your mailing lists.

When you set the "Email Column" setting the Report is considered to be a "Mailing List" Report and will display under the "All Mailing Lists" sidebar source on the Reports listing page.

Once you have those things in place, in your Notification Email sidebar you will see a Mailing Lists Relation field: https://share.barrelstrength.co/kpuYADQ9

Select "Add List" just like any other Relations field in Craft and a modal will appear where you will see all the Mailing List Reports as options to send to for your Notification Email.

While we do have plans to make this support larger list sizes, do note that the initial release of this feature is fairly simple and will be limited by whatever your server can handle when processing a single list in real-time, so if you have a larger list be sure to test that it can be reliable sent using this feature right now. Smaller lists should work fine, and we do have plans to make this a more robust feature in the future so list size is not a concern.

**Comment by johnj24** [comment]
Thanks, Ben. Was this possible in Craft 2 / Reports 0.10 or only in Craft 3 / Reports 1.0?

**Comment by BenParizek** [comment]
@johnj24 This was recently added in Sprout Reports for Craft 3.

**Comment by johnj24** [comment]
@BenParizek I've installed Reports 1.3.3 and I'm selecting `Email (email)` in the sidebar under "Mailing List". However, when I hit save and come back to the report, it's showing "none", like I had never made that change. No feedback is being given on why it can't be selected. Any ideas?

**Comment by BenParizek** [comment]
@johnj24 This issue should be fixed in the latest release. Sprout Email v4.3.0 and Sprout Reports v1.5.0.

Thanks for reporting.
