### ISSUE TITLE
Many requests fail on site due to issue with sprout-base-email/src/base/Mailer.php

### ISSUE THREAD

**Issue by admench** [barrelstrength/craft-sprout-email#152]
### Description (screenshots, logs, ...)

Argument 1 passed to craft\web\View::renderObjectTemplate() must be of the type string, null given, called in /home/forge/www.fira.co.uk/vendor/barrelstrength/sprout-base-email/src/base/Mailer.php on line 186

### Steps to reproduce

1. Many pages (not all) of the admin area return 500 server error. e.g. when saving a user, saving some notifications, saving some entries. I have a bunch of notifications that have been ported from a Craft v2 install.
2.

### Additional info

- Craft version: 3.4.15
- PHP version: 7.1.12
- Database driver & version:  Mysql 5.7.29
- Plugins & versions: 

```
barrelstrength/sprout-base                   5.1.3    Common libraries for Sprout Plugins for Craft CMS
barrelstrength/sprout-base-email             1.2.8    Common email libraries for Sprout Plugins for Craft CMS
barrelstrength/sprout-base-fields            1.3.5    Common fields libraries for Sprout Plugins for Craft CMS
barrelstrength/sprout-base-import            1.0.6    Common import libraries for Sprout Plugins for Craft CMS
barrelstrength/sprout-base-reports           1.4.5    Common reports libraries for Sprout Plugins for Craft CMS
barrelstrength/sprout-email                  4.2.0.1  Flexible, integrated email marketing and notifications.
barrelstrength/sprout-fields                 3.6.2    International, Craft-friendly field types.
barrelstrength/sprout-forms                  3.9.0.1  Simple, beautiful forms. 100% control.
barrelstrength/sprout-forms-google-recaptcha 1.2.0    Google Recaptcha for Sprout Forms
barrelstrength/sprout-lists                  3.0.2    Subscribe and unsubscribe to things.
barrelstrength/sprout-reports                1.3.3    Powerful custom reports.
```

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@admench I've moved this issue over to the Sprout Email repo to be able to process it better.

Did you recently update from Craft 2? This sounds like it could be a migration issue.

That line of code is processing the following fields below, so a good place to start would be to check and make sure none of these values are NULL for any of your Notifications in the database (`sproutemail_notifications`). I'm not sure what scenario would make them NULL, so that can be explored but let's try to track down where the issue might lie first:

- subjectLine
- fromName
- fromEmail
- replyToEmail
- defaultBody

Let me know what you find.

**Comment by admench** [comment]
Thanks Ben

I found that because I was using the example fields provided in the v2 docs (yes this is a v2 migration) that when switching over to using the `defaultBody` and updating my templates to use this, the error went away.
