### ISSUE TITLE
Fatal error when creating notification

### ISSUE THREAD

**Issue by johnnymueller** [barrelstrength/craft-sprout-email#153]
### Description (screenshots, logs, ...)
When trying to set up a new Notification I get the following error: "get_class() expects parameter 1 to be object, string given"

![Screen Shot 2020-04-28 at 4 18 35 PM](https://user-images.githubusercontent.com/369241/80543577-67d97800-896c-11ea-9165-2912c8bb123a.png)

### Steps to reproduce

1. Install plugin.
2. Click the "New Notification" button.

### Additional info

- Craft version: 3.4.15
- PHP version: 7.2.19
- Database driver & version: MySQL 5.7.26
- Plugins & versions: Sprout Email Lite

**Comment by BenParizek** [comment]
Thanks @johnnymueller. I can reproduce. I'll have a fix out shortly.

**Comment by BenParizek** [comment]
@johnnymueller I've just released v4.4.0 which should resolve this issue.
