### ISSUE TITLE
Template not found: sprout-email/notifications/preview/[id]

### ISSUE THREAD

**Issue by johnj24** [barrelstrength/craft-sprout-email#155]
### Description (screenshots, logs, ...)
I'm getting a 404 when trying to preview an email notification. I'm using the default Sprout Email notification template. Was a default template supposed to be installed?

### Steps to reproduce

1. Create a notification when an entry is created.
2. Preview the notification by clicking on the eye icon on the notification index page.

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.0.33
- Database driver & version:  
- Plugins & versions: Sprout Email 4.4

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks for reporting @johnj24. This is resolved in v4.4.2
