### ISSUE TITLE
Custom template path not saving

### ISSUE THREAD

**Issue by johnj24** [barrelstrength/craft-sprout-email#156]
### Description (screenshots, logs, ...)
I've tried adding custom templates to the template override dropdown on both the individual notification and the overall notification settings. In both areas when I try to add a path to the custom notification template (i.e., `_email/notifications/client-new-message`), the dropdown always reverts to Basic Notification (Sprout Email). I've also removed the underscore from the  `_email` folder to see if that makes a difference and it does not. Within the `_email/notifications/client-new-message` folder is a template named `email.html`, which I believe is the correct naming, but perhaps this is what's wrong?

### Steps to reproduce

1. Go to `Sprout Email > Settings > Notifications` or to a specific individual notification
2. Click on Default Email Template dropdown and select custom "Add Custom"
3. Add the folder path to the email notification template, i.e.: `_email/notifications/client-new-message`
4. Hit save or cmd+s
5. When the page reloads, the custom path is no longer there.

### Additional info

- Craft version: 3.4.17.1
- PHP version: 7.0.33
- Database driver & version:  
- Plugins & versions: Sprout Email 4.4

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
@johnj24 Thanks for reporting. This should be solved in v4.4.2.

I'd also recommend you review all your other email settings. There was a bug in a migration that could reset all shared Sprout settings. The only way to fix this is to roll-back and re-run the updates or retrieve your old settings from a backup database.

If you need to review the shared Sprout settings in the db directly, we are currently using a different method to save settings that Craft does with the Project Config. The Sprout Settings would be in the `sprout_settings` table and the below SQL statement reflects what they should roughly look like for Sprout Email:

```
INSERT INTO `craft_sprout_settings` (`id`, `model`, `settings`, `dateCreated`, `dateUpdated`, `uid`) VALUES
('3', 'barrelstrength\\sproutbasesentemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableSentEmails\":\"1\",\"sentEmailsLimit\":\"5000\",\"cleanupProbability\":\"1000\"}', '2020-05-16 15:29:27', '2020-05-16 16:16:42', '37ef68ad-9f77-41dd-a3ce-013bec6b1b65'),
('4', 'barrelstrength\\sproutbaseemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableNotificationEmails\":\"1\",\"emailTemplateId\":\"\",\"enablePerEmailEmailTemplateIdOverride\":\"\"}', '2020-05-16 15:29:27', '2020-05-16 16:06:09', 'eac7828c-c42a-4f7a-b705-10e2d3329103');
```

_Note: For reasons I won't go into here, we currently manage some settings in this non-standard way (as the default way doesn't solve all the needs for our particular plugin use-case with some shared features between plugins). I recognize that this abstraction has caused more problems than are ideal and we're currently exploring ways to update the way settings are handled in our plugins to figure out how we can solve these issue and get things working in a more Craft-native way._
