### ISSUE TITLE
Can't seem to save plugin settings

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-email#159]
### Description (screenshots, logs, ...)
I can't seem to have _some_ plugin settings. Refer to the video - https://d.pr/free/v/72mCUN

In addition, this was an upgrade from Craft 3.3 with Sprout Email 3.1.4 installed. All the settings for the plugin have been reset.

- Craft version: 3.4.19
- Sprout Email: 4.4.0

**Comment by BenParizek** [comment]
@engram-design  This issue should be resolved in v4.4.2, however:

I'd also recommend you review all your other email settings and any other Sprout plugins that may share settings like Forms, Reports, Email, and SEO. There was a bug in a migration that could reset all shared Sprout settings. The only way to fix this is to roll-back and re-run the updates or retrieve your old settings from a backup database.

If you need to review the shared Sprout settings in the db directly, we are currently using a different method to save settings that Craft does with the Project Config. The Sprout Settings would be in the `sprout_settings` table and the below SQL statement reflects what they should roughly look like for Sprout Email:

```
INSERT INTO `craft_sprout_settings` (`id`, `model`, `settings`, `dateCreated`, `dateUpdated`, `uid`) VALUES
('3', 'barrelstrength\\sproutbasesentemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableSentEmails\":\"1\",\"sentEmailsLimit\":\"5000\",\"cleanupProbability\":\"1000\"}', '2020-05-16 15:29:27', '2020-05-16 16:16:42', '37ef68ad-9f77-41dd-a3ce-013bec6b1b65'),
('4', 'barrelstrength\\sproutbaseemail\\models\\Settings', '{\"pluginNameOverride\":\"\",\"enableNotificationEmails\":\"1\",\"emailTemplateId\":\"\",\"enablePerEmailEmailTemplateIdOverride\":\"\"}', '2020-05-16 15:29:27', '2020-05-16 16:06:09', 'eac7828c-c42a-4f7a-b705-10e2d3329103');
```

_Note: For reasons I won't go into here, we currently manage some settings in this non-standard way (as the default way doesn't solve all the needs for our particular plugin use-case with some shared features between plugins). I recognize that this abstraction has caused more problems than are ideal and we're currently exploring ways to update the way settings are handled in our plugins to figure out how we can solve these issue and get things working in a more Craft-native way._
