### ISSUE TITLE
Template not found: sprout-email/sentemails

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-email#165]
I just want to have "Sent emails" enabled, so have turned off notifications. Clicking on Sprout Email in the sidebar throws a 404 error page for the above URL.

I can visit `/admin/sprout-email` and that shows me the Notifications screen, despite it being disabled.

I have Sprout Email and Sprout Forms installed. The latest versions of everything.

**Comment by engram-design** [comment]
Its just this line https://github.com/barrelstrength/craft-sprout-email/blob/v4/src/SproutEmail.php#L149

Needs to be changed to:
```
$parent['url'] = 'sprout-email/sentemails';
```

**Comment by BenParizek** [comment]
Hey @engram-design, I'll look into this.

If you are just using Sent Email, you should be able to install the standalone Sent Email plugin, then uninstall Sprout Email, and get rid of this layer altogether. Both Sprout Email and Sprout Sent Email use the same Element under the hood and check for one another's tables before uninstalling.

As a side note, I know you've been hit by several of these shared settings bugs. As of this week, we have a plan prototyped that I believe will help us remove all this complexity and just let a setting be a setting as you'd expect. It may take a couple of weeks to sort it all out but I wanted to let you know there is a plan in place to get this layer improved.

**Comment by engram-design** [comment]
Yep, aware of this, but this site has a Sprout Email license, so i figure we use that instead of paying for Sent Email again.

i'll be honest, it feels like we're stumbling across these a lot, and half of the issues the team doesn't report because we're under the pump. Not a update goes by without some form of Sprout plugin migration issue. Great to hear you're looking to simplify things, as even debugging on our end as fellow plugin developers is pretty difficult with so many links in the dependancy chain. Best of luck!

**Comment by BenParizek** [comment]
URL fixed in Sprout Email v4.4.6.

Yes, too much. The next steps for us are aimed at removing as much of the complexity as we can from that dependency chain around shared settings and permissions, and after that simplify the entire application architecture away from multiple composer-released packages that only Sprout uses to a mono-repo of some sort again. We had some challenges down that path in the past too, but we also ran into a lot fewer self-inflicted migration issues.
