### ISSUE TITLE
Plugin Name override doesn't work

### ISSUE THREAD

**Issue by bymayo** [barrelstrength/craft-sprout-email#166]
Entering a value in to `Plugin Name` in settings doesn't override the setting on the navigation.

<img width="768" alt="Screenshot 2020-06-03 at 15 01 52" src="https://user-images.githubusercontent.com/522877/83646128-2b242080-a5ab-11ea-801b-a1803b035c4e.png">

### Additional info

- Craft version: Craft CMS 3.4.22.1
- PHP version: 7.0.33
- Database driver & version: MySQL 5.7
- Plugins & versions: Sprout Email Pro 4.4.6

**Comment by BenParizek** [comment]
This is resolved in v4.4.7.

Thanks for reporting @bymayo
