### ISSUE TITLE
Error on Settings page, Craft 3.5

### ISSUE THREAD

**Issue by AndrewMac** [barrelstrength/craft-sprout-email#169]
### Description (screenshots, logs, ...)

Since updating to Craft 3.5 I get the following error when trying to load the "Settings" screen in Sprout Email

`Error: Call to a member function getAcceptsJson() on string in /Users/andrew/Sites/forge/spm/vendor/craftcms/cms/src/web/Controller.php:183
Stack trace:
#0 /Users/andrew/Sites/forge/spm/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-settings', Array)
#1 /Users/andrew/Sites/forge/spm/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('sprout/settings...', Array)
#2 /Users/andrew/Sites/forge/spm/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('sprout/settings...', Array)
#3 /Users/andrew/Sites/forge/spm/vendor/craftcms/cms/src/web/Application.php(279): yii\web\Application->handleRequest(Object(craft\web\Request))
#4 /Users/andrew/Sites/forge/spm/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#5 /Users/andrew/Sites/forge/spm/web/index.php(21): yii\base\Application->run()
#6 {main}`

### Steps to reproduce

1. Check you're on Craft 3.5
2. Try to load the settings page

### Additional info

- Craft version: 3.5.1 Pro
- PHP version: 7.4.2
- Database driver & version: MySQL
- Plugins & versions: Sprout Email 4.4.7

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by marionnewlevant** [comment]
Same here.
Craft: 3.5.4 Pro
Php 7.1.33
Sprout Email 4.4.7 (and other plugins)

**Comment by BenParizek** [comment]
@AndrewMac @marionnewlevant I'll take a look. We're currently polishing up a new major release that addresses several of the migration issues we've had over the last months and have not tested the current version of the plugin on Craft 3.5.

I'll update this thread if I can determine a temporary fix before we get that next release out.

**Comment by bentilden** [comment]
Having the same problem with Sprout Email, Sprout Reports and Sprout Forms.

Craft 3.5.1 Pro
PHP 7.3.9
Sprout Email 4.4.7
Sprout Forms 3.12.2
Sprout Reports 1.5.6

**Comment by BenParizek** [comment]
Hi folks. The Sprout plugins are not yet Craft 3.5 compatible. I wish I had a better way to indicate that in the upgrade process but I don't.

More context on where things stand here:
https://github.com/barrelstrength/craft-sprout-forms/issues/521#issuecomment-685744505

And if you're daring (to which I'd recommend caution), a temporary fix that may not address other Craft 3.5 issues is discussed here: 
https://github.com/barrelstrength/craft-sprout-reports/issues/98#issuecomment-685710988

**Comment by BenParizek** [comment]
This has been addressed in v4.4.8
