### ISSUE TITLE
Upgrade to Sprout Email 4.4.8 Fails

### ISSUE THREAD

**Issue by aladrach** [barrelstrength/craft-sprout-email#171]
When upgrading to, or installing fresh, Sprout Email 4.4.8, the following Composer error is displayed:
```
Problem 1
- Installation request for barrelstrength/sprout-email 4.4.8 -> satisfiable by barrelstrength/sprout-email[4.4.8].
- barrelstrength/sprout-email 4.4.8 requires barrelstrength/sprout-base ^6.0.2 -> no matching package found.
```

### Additional info
- Craft version: 3.5.5
- PHP version: 7.2
- Sprout Email version: 4.4.8

**Comment by BenParizek** [comment]
Thanks @aladrach. I've updated the tags and the dependencies should resolve correctly now.
