### ISSUE TITLE
Save Entry from front end not sending notification email.

### ISSUE THREAD

**Issue by keyurkadam** [barrelstrength/craft-sprout-email#179]
if i saved entry from backed then notification email are working fine. if i saved entry from frontend via form then plugin doesn't send any notification email and doesn't create any sent email entry.

- Craft version: 3.6.3
- Plugins & versions: Sprout email (4.4.9)

_For some issues, we may request that you send the following items to Support <sprout@barrelstrengthdesign.com>. If you feel your issue may fall in that category, feel free to send things over after you post this issue and reference the issue in your email._

- `composer.json`
- `storage/logs/web.log` (or a zip of the whole log folder)
- An export of your database (or, if you can't share the whole db, the specific Sprout tables)

**Comment by BenParizek** [comment]
Thanks @keyurkadam. I'll update this ticket #177 once we have a fix out.
