### ISSUE TITLE
Email notifications being sent twice during front end submission

### ISSUE THREAD

**Issue by joshwalsh** [barrelstrength/craft-sprout-email#183]
### Description (screenshots, logs, ...)

I have a Sprout Email notification being sent on Front End Submission, entry created.  This notification sends the message at the appropriate time, but sends it twice for each recipient.

I saw some chatter in the Craft Discord about issues with these hooks related to the entry draft workflow.  Perhaps its being run once for Draft and again on Publish or something like that?

This is causing us extra costs with SendGrid due to the double volume, as well as annoying our recipients with duplicate messages.  I'd appreciate any ideas you have for a workaround.

### Steps to reproduce

1. Create a notification with On Front End Submission as the trigger
2. Fill out the form on the Front End to trigger the workflow

<img width="370" alt="Screen Shot 2021-08-10 at 9 05 40 PM" src="https://user-images.githubusercontent.com/19155/128954605-cb158691-fe86-466b-882a-3a2d32c1685f.png">

### Additional info

- Craft version: 3.5.19.1
- PHP version: 7.4.12
- Database driver & version:  Mysql
- Plugins & versions: Latest Sprout Email and latest Guest Entries

**Comment by BenParizek** [comment]
@joshwalsh It looks like you have a custom event there as we don't support an "On Front-End Submission" event by default.

That said, there has been a moving target of changes happening with element save behavior between Craft 3.2 and 3.7.5 and that fact that something is happening twice makes me wonder if the custom code you have isn't restricting a scenario. Elements get saved multiple times in the background each time you save and multiples of times if you have a multi-site setup.

While I've just cut a new release that addresses some bugs that were just introduced around this, if you have a custom event, you may need to address this on your end. See my answer here for a summary of the changes that have happened in Craft that may matter in your situation and let me know if that doesn't help you get pointed in the right direction: https://craftcms.stackexchange.com/a/38169/115

**Comment by joshwalsh** [comment]
@BenParizek This is so silly of me, but I did not realize that the On Front-End Submission event was a custom event added by our team.  I inherited this code and made a poor assumption that it was part of your library.

Your stackexchange thread looks helpful as I debug our custom event.  

I appreciate the thorough response, especially since some of this is my own confusion.
