### ISSUE TITLE
Sprout Forms 'Send Test' Notification doesn't render mock object

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#50]
It seems the Send Test Notification in Sprout Forms fails when trying to render the template because the mock object does not create an object and the values in the template throw errors when accessed.

Specifically:

obect is an array
{%- set entry = object -%}

So this line fails
{%- set form = entry.form -%}

The mock object doesn't seem to get a value back from the DB because the Event _formIds value is never defined.

Can we be sure to populate _formIds from the event settings and update the template to ensure we don't throw an error if no object is found? Ideally, we could fall back and generate a new Form Entry model from Sprout Import seeds in the future, but just ensuring we don't throw an error would be a good first step.

**Comment by pdaleramirez** [comment]
@BenParizek I think you have fixed this already.
