### ISSUE TITLE
NotificationEmail not rendering object variables in Live Preview or Share Link

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#52]
Object syntax used in a custom field for a triggered event is rendering fine when sending an email. However it just renders the Twig code when viewing Live Preview or Share Link.

Can we generate a mock object for these scenarios?

### Steps to reproduce

See: http://share.barrelstrength.co/0d0M3f1N2A0w

### Additional info

- Craft version: Craft 3
- Sprout Email: 4.0.3-beta.3

**Comment by alexmglover** [comment]
@BenParizek Now that I think about it, it seems like this might have been a misunderstanding in how this is supposed to work. I set up the email template and added custom fields and everything is working now. I was trying to actually add template tags to the email, which is not how you intended for it to work as far as I can tell.

**Comment by pdaleramirez** [comment]
I don't think this is a bug but i added the feature anyway here https://github.com/barrelstrength/craft-sprout-base/commit/b8f8151cb73b59c833bfbe29c30b961940bd289b
