### ISSUE TITLE
New Notification button throws singleEmail error

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#55]
Setting unknown property: barrelstrength\sproutbase\app\email\records\NotificationEmail::singleEmail

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_dmuz)

**Comment by pdaleramirez** [comment]
There is a bug when migrating from craft2 to craft3. I think he is migrating from craft2 to craft3. We need to release the bug fix for this issue #53 .
