### ISSUE TITLE
Add support for CC and BCC fields in Notification Emails

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#65]
See: http://share.barrelstrength.co/795fef3f01e4

**Comment by pdaleramirez** [comment]
I finished this feature committed on bcc-cc branch 
https://github.com/barrelstrength/craft-sprout-base/tree/feature/bcc-cc
https://github.com/barrelstrength/craft-sprout-email/tree/feature/bcc-cc
