### ISSUE TITLE
object.formName is not populated on email sends (works in preview)

### ISSUE THREAD

**Issue by jamesmacwhite** [barrelstrength/craft-sprout-email#67]
### Description

I created an email template which is shared across multiple Sprout Forms, as the content is virtually identical, aside from its origin i.e. different form name. I debugged the object variable and found `formName` was available to obtain the form name dynamically, saves having to duplicate a template twice. So I used `object.formName` in the template which works in the preview. However on real sends, it is not populated/blank (assuming null). Is there any way to get the form name dynamically that will work with an actual email send?

### Steps to reproduce

1. Output `object.formName` in a Sprout Emails template
2. Setup a form to use this template where this object is either outputted directly or stored in a variable and then outputted.
3. When an email is generated from this template, `object.formName` is not populated and will be blank.

### Additional info

- Craft version: 2.7.2
- PHP version: 7.1
- Plugins & versions: 3.1.0

**Comment by BenParizek** [comment]
@jamesmacwhite We'll look into this and let you know what we find.

**Comment by BenParizek** [comment]
@jamesmacwhite Looks like this may be a bug. We can recreate it. We'll release a fix when we can. In the meantime, you should be able to work around this by updating to use the following syntax:

```
{{ object.getForm().name }}
```

**Comment by jamesmacwhite** [comment]
@BenParizek Thanks for investigating this. I'll try with the alternative syntax for now.
