### ISSUE TITLE
PHP 7.2 count error

### ISSUE THREAD

**Issue by andrelopez** [barrelstrength/craft-sprout-email#70]
<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_eu63)

**Comment by andrelopez** [comment]
@pdaleramirez Please check the front link, the user says that he is still having the issue.

**Comment by andrelopez** [comment]
The user still have this error. @pdaleramirez

**Comment by pdaleramirez** [comment]
I have fixed this issue here https://github.com/barrelstrength/craft-sprout-email/tree/bugfix/caft2/countable i added is_array to all code that has count in an if statement to make sure we don't encounter same issue again. I also tested this by migrating it to sprout email 2.5 to v3
