### ISSUE TITLE
Add support for Entry Types in Save New Entry Notification Event

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#72]

**Comment by johnwbaxter** [comment]
I would love to see this!!!!!

**Comment by BenParizek** [comment]
@johnwbaxter I just realized this is now possible using the Send Rule feature on Email Events.

By default the Send Rule is set to "Always" but you can update it to a custom pattern, such as:

``` twig
{{ object.getType().handle == 'entryType' }}
```

For example, if this was the Send Rule for the "When an entry is saved" trigger, the trigger would be further limited to only send when your statement returned true. I'll get a page up on this in the docs soon.

**Comment by BenParizek** [comment]
Send Rule is now documented on the Notification Events page:
https://sprout.barrelstrengthdesign.com/docs/email/notification-events.html#send-rule
