### ISSUE TITLE
Email Notification triggered when saving a Draft

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#79]
Currently, the Save Entry Notification Event triggers when a draft is being saved. The default event should only trigger when a live, enabled entry is being saved.

### Notify

- [x] Mathias Syversen on Slack

**Comment by pdaleramirez** [comment]
The Entries Save event does not trigger adding or saving draft entries but it does trigger on entries when a disabled status. I have modified it to only trigger live or enabled entries.

**Comment by BenParizek** [comment]
This will also be addressed by targeting the `Element::SCENARIO_LIVE` condition:
https://github.com/barrelstrength/craft-sprout-email/issues/76
