### ISSUE TITLE
Save User Notification Event should allow an admin group to be selected

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#80]
Currently, the Save User event requires a User Group to exist or it doesn't show any settings for which user group to select and doesn't get triggered.

Can we add a separate checkbox option for users to select for Admins. This Admin checkbox will always be displayed so it will be clear if no options are selected when trying to send to a group of users or Admins.

**Comment by pdaleramirez** [comment]
@BenParizek There is no admin group but an admin role instead. I added a adminUsers lightswitchField in the UserSave setting. The setting always displays event no user group is created.

The notification triggers if the adminUsers setting is ON and the user being saved is an **admin** users. If it is OFF it will run the normal behavior.

Here are my tests on different cases:
**Settings - empty group, trigger admin OFF**
no group, not admin : not notify
no group, admin : not notify

**Settings - empty group, trigger admin ON**
no group, not admin : not notify
no group, admin : notify

**Settings - group one checked, trigger admin OFF**
group one, not admin : notify
group one, admin : notify
group two, not admin : not notify
group two, admin : not notify

**Settings - group one checked, trigger admin ON**
group one, not admin : notify
group two, not admin : not notify
group two, admin : notify
group two, not admin : not notify
