### ISSUE TITLE
Clean up CampaignType usage

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#87]
We've refactored how CampaignEmail and CampaignType are needed throughout the code. Make sure we're only passing CampaignEmail to the appropriate methods and getting CampaignType via the CampaignEmail class such as `$campaignEmail->getCampaignType()`

**Comment by pdaleramirez** [comment]
- Removed $campaignType reference on Mark Sent feature for copyPaste mailer and tested the feature again after changes has been made
