### ISSUE TITLE
Address in mailbox given [] does not comply with RFC 2822

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#94]
This error is show if recipients is blank and you hit "Prepare Test"

**Comment by pdaleramirez** [comment]
I fixed this bug. The problem was the return value of getEmailTemplateId is set to return string. I have it return as blank string if it is null. https://github.com/barrelstrength/craft-sprout-base/commit/f4f5d94c856d5b619c57d6f4c906512b72381afb
