### ISSUE TITLE
Only first three notifications being sent

### ISSUE THREAD

**Issue by BenParizek** [barrelstrength/craft-sprout-email#95]
DB attached in support conversation:

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gr9n)

**Comment by pdaleramirez** [comment]
@BenParizek  I added this fix here https://github.com/barrelstrength/craft-sprout-email/commit/e20d13e8de8f06c7f3766ec829fe2aad1e521591 this commit will skip any invalid emails and continue sending the valid one. This fix is already shipped on craft 3 version. 

This is on the https://github.com/barrelstrength/craft-sprout-email/tree/bugfix/caft2/countable branch there are also  other bug fixes on that branch
