### ISSUE TITLE
Plugin throws an error when trying to send Commerce emails

### ISSUE THREAD

**Issue by engram-design** [barrelstrength/craft-sprout-email#97]
### Description

I'm getting the following error when an email is sent from Commerce. It actually stops the email being sent. Its a tricky one on production, as this works fine locally, but might have something to do with our `testToEmailAddress` config override. Using Mailgun as the email transport.

All other emails are sent fine, we have Sprout Forms, and a custom plugin, all send fine.

`2019-01-30 10:45:55 [-][16244][-][error][craft\commerce\services\Emails::sendEmail] Email “Order Received Notification” could not be sent for order “f78a094”. Error: Creating default object from empty value /home/forge/mygoodnessorganics.com.au/vendor/barrelstrength/sprout-email/src/services/SentEmails.php:72`

FYI, I have created a fork that fixes this, because its an urgent issue for a production site. https://github.com/engram-design/craft-sprout-email/commit/f8eea828c57e097299e437eb9fdd4995cf7cf0ea

### Steps to reproduce

1. Complete checkout through Commerce

### Additional info

Craft CMS: 3.0.36
Craft Commerce: 2.0.0-beta.15
Sprout Email: v4.0.0-beta.7

**Comment by pdaleramirez** [comment]
@BenParizek I could not recreate the issue. Even with the exact version given above. I may need the DB to troubleshoot the issue more.

**Comment by BenParizek** [comment]
@engram-design We've also been unable to recreate using the `testToEmailAddress` override setting.

If you can share your database, could you send it over to sprout@barrelstrengthdesign.com? Or if not the whole db, at least the sproutemail tables?

**Comment by engram-design** [comment]
@BenParizek Sure thing, I'll get a cut-down version sent over shortly.

**Comment by BenParizek** [comment]
@engram-design I expect this may be fringe enough that it fell by the wayside. Would you like to provide any more info on this to help us dig deeper or should we consider it a potential environment issue right now and re-open if it resurfaces?

**Comment by engram-design** [comment]
Yep, just spun this up on a brand new install and can't reproduce, so may very well be specific to this particular site. If its more of an issue, I'll report back!
